# Generated by Django 3.0.5 on 2020-05-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200503_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='No Decription Available', max_length=250),
        ),
    ]
