# Generated by Django 3.0.5 on 2020-05-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='message',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
