# Generated by Django 3.0.5 on 2020-05-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200503_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
