# Generated by Django 3.0.5 on 2020-05-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200503_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='imgurl',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/1024px-No_image_available.svg.png', max_length=150),
        ),
    ]
