# Generated by Django 3.0.5 on 2020-05-03 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='imgurl',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='message',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='name',
        ),
        migrations.AddField(
            model_name='cart',
            name='productid',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, to='shop.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='imgurl',
            field=models.ImageField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/No_image_available.svg/1024px-No_image_available.svg.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='message',
            field=models.CharField(default='', max_length=250),
        ),
    ]
