# Generated by Django 3.0.5 on 2020-05-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200503_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='message',
            field=models.CharField(default=' ', max_length=250),
        ),
    ]
