# Generated by Django 3.0.5 on 2020-05-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200503_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='message',
        ),
    ]
